# Generated by Django 6.0.2 on 2026-02-10 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10, verbose_name='类型')),
                ('shares', models.IntegerField(verbose_name='份额数量')),
                ('filled_shares', models.IntegerField(default=0, verbose_name='已成交份额')),
                ('price_per_share', models.FloatField(verbose_name='单价(积分/份)')),
                ('status', models.CharField(choices=[('pending', '挂单中'), ('partial', '部分成交'), ('filled', '已成交'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='状态')),
                ('expire_time', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.greencertificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '交易挂单',
                'verbose_name_plural': '交易挂单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='议价留言')),
                ('proposed_price', models.FloatField(verbose_name='建议价格')),
                ('is_accepted', models.BooleanField(default=None, null=True, verbose_name='是否接受')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_negotiations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='trading.order')),
            ],
            options={
                'verbose_name': '议价记录',
                'verbose_name_plural': '议价记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField(verbose_name='成交份额')),
                ('price_per_share', models.FloatField(verbose_name='成交单价')),
                ('total_price', models.FloatField(verbose_name='总价')),
                ('block_hash', models.CharField(blank=True, max_length=128, verbose_name='区块哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='trading.order')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.greencertificate')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='trading.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '成交记录',
                'verbose_name_plural': '成交记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
