# Generated by Django 6.0.2 on 2026-02-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='区块序号')),
                ('timestamp', models.FloatField(verbose_name='时间戳')),
                ('data', models.JSONField(verbose_name='区块数据')),
                ('previous_hash', models.CharField(max_length=128, verbose_name='前一区块哈希')),
                ('hash', models.CharField(max_length=128, verbose_name='区块哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '区块',
                'verbose_name_plural': '区块',
                'ordering': ['index'],
            },
        ),
    ]
