# Generated by Django 6.0.2 on 2026-02-10 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=64, unique=True, verbose_name='绿证编号')),
                ('total_kwh', models.FloatField(default=1000, verbose_name='对应发电量(kWh)')),
                ('total_shares', models.IntegerField(default=1000, verbose_name='总份额')),
                ('generated_date', models.DateField(auto_now_add=True, verbose_name='生成日期')),
                ('expire_date', models.DateField(verbose_name='过期日期')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('used', '已使用')], default='active', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '绿色电力证书',
                'verbose_name_plural': '绿色电力证书',
            },
        ),
        migrations.CreateModel(
            name='PVDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('building', models.CharField(max_length=50, verbose_name='所属楼栋')),
                ('capacity_kw', models.FloatField(verbose_name='装机容量(kW)')),
                ('status', models.CharField(choices=[('normal', '正常'), ('fault', '故障'), ('maintenance', '维护中')], default='normal', max_length=20, verbose_name='运行状态')),
                ('installed_date', models.DateField(verbose_name='安装日期')),
            ],
            options={
                'verbose_name': '光伏设备',
                'verbose_name_plural': '光伏设备',
            },
        ),
        migrations.CreateModel(
            name='CertShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='份额数量')),
                ('source', models.CharField(choices=[('initial', '初始分配'), ('trade', '交易所得')], default='initial', max_length=20, verbose_name='来源')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='是否冻结')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_shares', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='certificates.greencertificate')),
            ],
            options={
                'verbose_name': '绿证份额',
                'verbose_name_plural': '绿证份额',
            },
        ),
        migrations.AddField(
            model_name='greencertificate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.pvdevice'),
        ),
        migrations.CreateModel(
            name='PowerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='发电日期')),
                ('kwh', models.FloatField(verbose_name='发电量(kWh)')),
                ('is_valid', models.BooleanField(default=True, verbose_name='数据有效')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='certificates.pvdevice')),
            ],
            options={
                'verbose_name': '发电记录',
                'verbose_name_plural': '发电记录',
                'unique_together': {('device', 'date')},
            },
        ),
    ]
