# Generated by Django 6.0.2 on 2026-02-10 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('resident', '居民'), ('property', '物业管理员'), ('admin', '系统管理员')], default='resident', max_length=20, verbose_name='角色')),
                ('unit_number', models.CharField(blank=True, max_length=50, verbose_name='居住单元号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('area', models.FloatField(default=0, verbose_name='居住面积(㎡)')),
                ('points', models.IntegerField(default=10000, verbose_name='虚拟积分')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
