# Generated by Django 4.2.30 on 2026-04-22 01:56

from django.db import migrations, models


def merge_property_into_admin(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(role='property').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(merge_property_into_admin, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("resident", "居民"), ("admin", "管理员")],
                default="resident",
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
